# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_PXA3xx)		+= mfp.o
obj-$(CONFIG_ARCH_MMP)		+= mfp.o

obj-$(CONFIG_PXA_SSP)		+= ssp.o
obj-$(CONFIG_PLAT_PXA)		+= driver.o
obj-$(CONFIG_PXA_DRIVER_KUNIT_TEST) += pxa-driver-test.o
